FROM oven/bun:1

WORKDIR /workspace

COPY package.json ./
COPY bun.lockb* ./

RUN bun install

COPY . .

RUN bun run tests/e2e/scripts/generate-monorepo.ts generate

CMD ["bun", "run", "tests/e2e/scripts/test-exec.ts"]
